### ISSUE TITLE
Issue with recycler view and scroll

### ISSUE THREAD

**Issue by bhaumik2712** [brucetoo/PinterestView#2]
Hello,
When I scroll recyclerview, pinterest view shows ( no long press).
How can I fix this issue?

Thanks & Regards,
Bhaumik

**Comment by brucetoo** [comment]
Did you run branch [reyclerview-demo](https://github.com/brucetoo/PinterestView/tree/reyclerview-demo)  ?

**Comment by bhaumik2712** [comment]
yes

**Comment by bhaumik2712** [comment]
also you can reproduce same by scrolling recyclerview fast.

**Comment by brucetoo** [comment]
Hmmm...It's weird..Not matter how fast i scroll, it's not be reproduced....Maybe need more information.

**Comment by bhaumik2712** [comment]
![issue](https://cloud.githubusercontent.com/assets/11713742/10882440/c3ae55ee-8190-11e5-822f-a8e89e5ab450.gif)

are you able to reproduce such kind of issue?

**Comment by brucetoo** [comment]
It's pretty weird,how could that happen? You can print some logs to see what cause this problem ?By the way,i double-checked,but can not reproduce.What kind of phone you test? phone's version ?

**Comment by bhaumik2712** [comment]
I am using Motorola X having android OS v5.1.

**Comment by bhaumik2712** [comment]
When I scroll recyclerview , I am getting following logs

com.brucetoo.pinterestview I/PinterestView: rightBottomRect
com.brucetoo.pinterestview I/computeChildFrame:: Rect(-8, 611 - 71, 691)
com.brucetoo.pinterestview I/PinterestView: rightBottomRect
com.brucetoo.pinterestview I/computeChildFrame:: Rect(169, 129 - 249, 209)
com.brucetoo.pinterestview I/PinterestView: ACTION_UP--single press---436.0
com.brucetoo.pinterestview I/PinterestView: rightBottomRect
com.brucetoo.pinterestview I/computeChildFrame:: Rect(1, 412 - 81, 492)
com.brucetoo.pinterestview I/PinterestView: ACTION_UP--single press---292.0
com.brucetoo.pinterestview I/PinterestView: rightBottomRect
com.brucetoo.pinterestview I/computeChildFrame:: Rect(85, 413 - 165, 493)
com.brucetoo.pinterestview I/PinterestView: ACTION_UP--single press---373.0

**Comment by brucetoo** [comment]
Thank you,i will check the code recently.

**Comment by bhaumik2712** [comment]
Thanks for the support  :)

**Comment by brucetoo** [comment]
I just checked the code,still can't find which cause this problem,Can you test in simulator to see if this will happen ?  My nexus 5(os 5.0) and nexus 5X (os. 6.0) work fine.

**Comment by bhaumik2712** [comment]
I just checked in Nexus 5 (os 5.0) emulator and it has same issue.

**Comment by bhaumik2712** [comment]
I have solved issue using gesture detector.
I will send you pull request soon..
Thanks for the support :)

Cheers
Bhaumik

**Comment by brucetoo** [comment]
Thanks for your feedback, and sorry about that i don' t have enough time to solve this issue(In fact,i could not reproduce),
and Welcome PR.
