### ISSUE TITLE
Problem with view

### ISSUE THREAD

**Issue by ghost** [brucetoo/PinterestView#4]
if i use with a specific height, like 300dp because i have to use this menu only in a part of screen, i have some rendering problem because the point where i touch and the centerview isn't the same, the centerview is lower than touch point.

**Comment by brucetoo** [comment]
PinterestView has some limitation like where there is ToolBar or not,may be the better way is your job to control where the centerview is according to some special situations. BTW,I dont think my solution is a good way.

**Comment by brucetoo** [comment]
check out the newest code,this was be fixed
