### ISSUE TITLE
Menu not show correct position if not use  Toolbar (removed)

### ISSUE THREAD

**Issue by amaydiam** [brucetoo/PinterestView#5]
I found bugs, Menu is not show correct position if not use  Toolbar (removed). Please Fix it :)

**Comment by brucetoo** [comment]
I have a temporary way to work this out.  mCenterY plus dp2px(48) (ToolBar height)...And i still dont have a better idea,may there are better way to achieve PinterestView

**Comment by brucetoo** [comment]
Now this bug fixed
